#!groovy
pipeline {
    options {
        skipDefaultCheckout(true)
    }
    agent {
        label {
            label ""
            customWorkspace "/var/jenkins_home/workspace/importweahter/"
        } // Ende Label
    } // Ende Agent
    triggers {
        //Execute weekdays every four hours starting at minute 0
        cron('25 1 * * *')
        pollSCM('1 1 * * *')
    } // Ende Triggers
     stages {
        stage('Prepare') {
            steps {
                notifyBuild('STARTED')
                // GIT submodule recursive checkout
                checkout scm: [
                        $class: 'GitSCM',
                        branches: scm.branches,
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [[$class: 'SubmoduleOption',
                                      disableSubmodules: false,
                                      parentCredentials: false,
                                      recursiveSubmodules: true,
                                      reference: '',
                                      trackingSubmodules: false]],
                        submoduleCfg: [],
                        userRemoteConfigs: scm.userRemoteConfigs
                ]
                sh 'git submodule update --init --recursive'
                sh 'git submodule update'
                // copy managed files to workspace
                sh 'mkdir -p bin'
                sh 'mkdir -p coverage'
            }
        }
		stage('build frameworks') {
		    steps {
                parallel (
                    "curlpp" : {
		            sh """
			    cd frameworks/curlpp
                            mkdir -p build
                            cd build
                            cmake ..
                            make
                            sudo make install
			    """
                    }

				) // Ende Parallel
            } // Ende Framework Steps
        } // Ende Stage build framework

        stage('build') {
            steps {
                parallel (
                    "ReadWeatherSource" : {
                        sh 'make'
                    }
		          )
		        }
		    } // Ende build


     } // Ende Stages
    post {
        always {
            deleteDir()
            notifyBuild(currentBuild.result)
        }
    } // Ende Post


 } // Ende Pipeline

def notifyBuild(String buildStatus = 'STARTED') {
  // build status of null means successful
  buildStatus =  buildStatus ?: 'SUCCESSFUL'
 
  // Default values
  def colorName = 'RED'
  def colorCode = '#FF0000'
  def subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
  def summary = "${subject} (${env.BUILD_URL})"
  def details = """<p>STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
    <p>Check console output at "<a href="${env.BUILD_URL}">${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>"</p>"""
 
  // Override default values based on build status
  if (buildStatus == 'STARTED') {
    color = 'YELLOW'
    colorCode = '#FFFF00'
  } else if (buildStatus == 'SUCCESSFUL') {
    color = 'GREEN'
    colorCode = '#00FF00'
  } else {
    color = 'RED'
    colorCode = '#FF0000'
  }
 
  // Send notifications
  slackSend (color: colorCode, message: summary)
 
